femeie(ioana).
femeie(dana).
femeie(maria).
barbat(ion).
barbat(dan).
barbat(marius).
parinte(ioana,dan).
parinte(ion,dan).
parinte(dan,maria).
parinte(dan,marius).
parinte(dana,maria).
parinte(dana,marius).
tata(X,Y):-barbat(X),parinte(X,Y).
mama(X,Y):-femeie(X),parinte(X,Y).
fiica(X,Y):-femeie(Y),parinte(X,Y).
fiu(X,Y):-barbat(Y),parinte(X,Y).
bunic(X,Y):-barbat(X),parinte(X,Z),parinte(Z,Y).
bunica(X,Y):-femeie(X),parinte(X,Z),parinte(Z,Y).
nepot(X,Y):-bunic(X,Y),fiu(_,Y).
nepot(X,Y):-bunica(X,Y),fiu(_,Y).
nepoata(X,Y):-bunic(X,Y),fiica(_,Y).
nepoata(X,Y):-bunica(X,Y),fiica(_,Y).
